### ISSUE TITLE
Vẽ biểu đồ UML Use case: Phân rã use case "Manager"

### ISSUE THREAD

**Issue by Sinnerjudging** [Sinnerjudging/WebStore#10]

**Comment by balx8** [comment]
https://drive.google.com/file/d/1ES60DFkfZAT3tn6EaD3oZZ-FvT2onbIf/view?usp=sharing

**Comment by Khiemnt0403** [comment]
https://drive.google.com/file/d/1ue844rWc7xlKfkMmgWWSg027oYPrkNSb/view?usp=sharing

**Comment by balx8** [comment]
https://drive.google.com/file/d/1ES60DFkfZAT3tn6EaD3oZZ-FvT2onbIf/view?usp=sharing

**Comment by huynhducmanh2005** [comment]
https://drive.google.com/file/d/1ue844rWc7xlKfkMmgWWSg027oYPrkNSb/view?usp=sharing
