### ISSUE TITLE
Vẽ biểu đồ UML Use case: Phân rã use case "Staff"

### ISSUE THREAD

**Issue by Sinnerjudging** [Sinnerjudging/WebStore#12]

**Comment by Sinnerjudging** [comment]
https://drive.google.com/file/d/1J7w7ldUazPPLhUfeZZ-0RvpQF1hURK84/view?usp=sharing

**Comment by thaothuong2005** [comment]
https://drive.google.com/file/d/10YMRE9zN0xgnfbIThKd0jQ5tcWCJcjga/view?usp=sharing
