### ISSUE TITLE
Vẽ biểu đồ UML Use case: Phân rã use case "Customer"

### ISSUE THREAD

**Issue by Sinnerjudging** [Sinnerjudging/WebStore#13]

**Comment by balx8** [comment]
https://drive.google.com/file/d/1fl8GcZr5ReqfnUa8Dr99ViGTCw1xENDE/view?usp=sharing

**Comment by huynhducmanh2005** [comment]
https://drive.google.com/file/d/1fl8GcZr5ReqfnUa8Dr99ViGTCw1xENDE/view?usp=sharing

**Comment by huynhducmanh2005** [comment]
https://drive.google.com/file/d/1fl8GcZr5ReqfnUa8Dr99ViGTCw1xENDE/view?usp=sharing
