### ISSUE TITLE
Giỏ hàng

### ISSUE THREAD

**Issue by Sinnerjudging** [Sinnerjudging/WebStore#9]
Trang này quản lý tất cả các đơn hàng của khách hàng và thanh toán đơn hàng

**Comment by balx8** [comment]
![image](https://github.com/user-attachments/assets/09caa44a-6334-43cc-8a45-1c864f4730e3)

**Comment by thaothuong2005** [comment]
![image](https://github.com/user-attachments/assets/3c892f29-8509-4114-8f77-b784b221199d)
